# Use an OpenJDK base image
FROM amazoncorretto:17

# Sets the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by the Maven build to the container
COPY target/task-management-api-0.0.1-SNAPSHOT.jar app.jar

# Sets the environment variable for Spring Boot
# ENV JAVA_OPTS=""
# NV WAIT_VERSION 2.7.3

# Install docker-compose-wait
# ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
# RUN chmod +x /wait

# Exposes the port that the application uses
EXPOSE 8080

# Command to run Spring Boot application with/without docker-compose-wait
#ENTRYPOINT ["/wait", "java", "$JAVA_OPTS", "-jar", "app.jar"]
ENTRYPOINT ["java", "-jar", "app.jar"]