version: '3.8'

services:
  app:
    build: .
    container_name: task-management-api-app-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:mydb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"